# Generated by Django 2.0.3 on 2018-03-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('img_path', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('count', models.CharField(max_length=5)),
                ('totalprice', models.FloatField()),
                ('ctime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=32)),
                ('img_path', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('Stock', models.CharField(max_length=10)),
                ('is_host', models.BooleanField()),
                ('recommend', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product_class',
            fields=[
                ('pcid', models.AutoField(primary_key=True, serialize=False)),
                ('sort', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('dtime', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.Product_class'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
    ]
