# Generated by Django 2.0.3 on 2018-03-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('img_path', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('count', models.CharField(max_length=5)),
                ('totalprice', models.FloatField()),
                ('ctime', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User')),
            ],
        ),
    ]
