# Generated by Django 2.0.3 on 2018-03-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_order_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_info',
            old_name='oid',
            new_name='cid',
        ),
    ]
