# Generated by Django 2.0.3 on 2018-03-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180314_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_info',
            old_name='cid',
            new_name='oid',
        ),
    ]
