# Generated by Django 2.0.3 on 2018-03-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180314_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider_Porduct',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('url_link', models.CharField(max_length=100)),
                ('img_path', models.CharField(max_length=100)),
            ],
        ),
    ]
