# Generated by Django 2.0.3 on 2018-03-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_spider_porduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider_porduct',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
