# Generated by Django 2.0.3 on 2018-03-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180315_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider_porduct',
            name='img_path',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='spider_porduct',
            name='url_link',
            field=models.CharField(max_length=1000),
        ),
    ]
