# Generated by Django 2.0.3 on 2018-03-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_spider_porduct_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider_porduct',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.Spider_Porduct_item'),
        ),
    ]
